services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: hass_core_dev
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
    environment:
      - TZ=Europe/Rome