services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: hass_core_dev
    restart: "no"
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
    environment:
      - TZ=Europe/Rome
    networks:
      v2c-dev:
        aliases:
          - homeassistant

networks:
  v2c-dev:
    name: v2c-dev
    external: true
